### ISSUE TITLE
Something went wrong. More: Can not send privacy token tx

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#10]
- locked money/ wrong money -> how to fix? -> change UI message
- talk to chain team?

**Comment by 0xSiris** [comment]
We will show the root cause of the error. For example: 

- Please wait for your previous transaction to finish processing. Simply try again later. (-4002: -1022)
- It looks like your transaction didn't go through.  Please wait a few minutes and try again (-100)
- Something went wrong. Please try again.
