### ISSUE TITLE
Deposit TOMO error

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-wallet#14]
### FROM
https://t.me/FlippaCoin

### BUG

Hi Duy,

I deposit Tomo to address generated by the wallet but then pending transaction didn't register. The TOMO have gone to the address but hasn't synced or registered in wallet?

TXID:

0x77e00c652e7916ec813886f017c09d110856dad1491b46330847d2e50baeb5e4

"Image" no pending deposit has been registered.

Incognito address generated:
0x345069a04F7EcE0d7910f523dbeCD85963BE636c

Funds are there. I want to run a node and test the network.

![image](https://user-images.githubusercontent.com/4691695/68082967-32a30180-fdf1-11e9-8755-951eb7515baa.png)

![image](https://user-images.githubusercontent.com/4691695/68082970-36cf1f00-fdf1-11e9-9199-aef6051ed7a3.png)

![image](https://user-images.githubusercontent.com/4691695/68082974-3afb3c80-fdf1-11e9-9c6b-5438cf9874ec.png)

**Comment by duyhtq** [comment]
### USER PINGED AGAIN

FlippaCoin (🌕 Rogue Planet MN), [Nov 3, 2019 at 7:42:25 PM]:
Hi Duy,

no outside tomo chain deposits still>

i sent another after jamie said theyd fixed the bug but that hasnt arrived yet either

0x77e00c652e7916ec813886f017c09d110856dad1491b46330847d2e50baeb5e4

been a day for the original and 10hrs for the second

cheers

**Comment by Just-m** [comment]
The bug that delayed transactions seemed addressed rather than fixed. Read that later on in the chat.

At this time, he did reveice tokens, but apparently a much larger amount. As stated above, he sent 2001 TOMO first, and 10 TOMO later on
Seems like the first deposit is registered 3 times, and the second one twice.
Could be a simple register/display error, or transactions are being performed multiple times. 

![image](https://user-images.githubusercontent.com/5701553/68117958-11303b80-feff-11e9-80c3-09a63f4053c8.png)

**Comment by annie-incognito** [comment]
the tomorrow build should fix this. currently we duplicated the amount
