### ISSUE TITLE
Can not send privacy token tx

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-wallet#288]
From: @chuckyfunky
Description:
It is on pDex. App 3.3.9 Android 9
![image](https://user-images.githubusercontent.com/57339122/70767207-e6a19000-1d92-11ea-8dcf-1d5e3956091b.png)
![image](https://user-images.githubusercontent.com/57339122/70767210-ea351700-1d92-11ea-87a1-cfcde0d7406a.png)
![image](https://user-images.githubusercontent.com/57339122/70767213-ec977100-1d92-11ea-90c4-7938c61bab5a.png)

**Comment by 0xSiris** [comment]
We will show the root cause of the error. For example: 

- Please wait for your previous transaction to finish processing. Simply try again later. (-4002: -1022)
- It looks like your transaction didn't go through.  Please wait a few minutes and try again (-100)
- Something went wrong. Please try again.
