### ISSUE TITLE
import private key showinng -> account already existed

### ISSUE THREAD

**Issue by annie-incognito** [incognitochain/incognito-wallet#29]
Just an FYI.  When you backup the current private key, install the updated app, and then go to import based off of the backed up private key you are told something in the form that an account already exists with that key.  I found that I had to create a temp account, then delete the original account with the backed up private key and then perform the import.  After completing successfully, I then deleted the temp account.

... and I then could delete the original account that I backed up the private key from.
I was unable to delete the original account since it was the only account that existed until I created the temp account.
Just thought users might like to know this.

**Comment by Just-m** [comment]
Someone mentioned it today too

![image](https://user-images.githubusercontent.com/5701553/68146577-98e66c00-ff38-11e9-81e1-f706a91cedc6.png)

**Comment by Just-m** [comment]
Another workaround seems to be:
- uninstall the wallet app
- shut down the device completely
- start the device
- install the wallet app

**Comment by Dream0895** [comment]
Hi @annie-incognito ,

After reading this comment  such as:
"Just an FYI. When you backup the current private key, install the updated app, and then go to import based off of the backed up private key you are told something in the form that an account already exists with that key. I found that I had to create a temp account, then delete the original account with the backed up private key and then perform the import. After completing successfully, I then deleted the temp account.

... and I then could delete the original account that I backed up the private key from.
I was unable to delete the original account since it was the only account that existed until I created the temp account.
Just thought users might like to know this."

If user only updates app without deleting app as above. This is NOT bug. When updating app, existed account is saving. So, User canNOT import the backup private key again. 

I also checked case which is deleted app. It's working well. So, please help me to close this ticket.

Please let me know if you have any.
Many thanks.
